# =================================================================================
# == OPTIMUS - JVM & GRADLE CONFIGURATIONS                                       ==
# == Layer 2: Increased Thread Stack Size (-Xss16m) appended to JVM arguments.   ==
# == This prevents java.lang.StackOverflowError during deep AST recursive        ==
# == parsing by R8 when processing complex bytecode from Meta Audience Network.  ==
# =================================================================================
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M -Xss16m
org.gradle.parallel=true
unityStreamingAssets=**STREAMING_ASSETS**

# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**

# [Optimus] Suppress the warning regarding AGP 7.4.2 testing limits with compileSdk 35
android.suppressUnsupportedCompileSdk=35

android.jetifier.ignorelist=annotation-experimental-1.4.0.aar