// --- AUTO GENERATED BY OPTIMUS SYSTEM ---
// DO NOT EDIT MANUALLY. USE ADCONFIG INSPECTOR TO REGENERATE.

public enum PlacementType
{
    None = 0,
    AdmobAppOpenDefault = 10,
    AdmobBannerDefault = 20,
    AdmobInterDefault = 30,
    AdmobInterOpen = 31,
    AdmobMrecDefault = 40,
    AdmobMrecIAP = 41,
    AdmobMrecOpen = 42,
    AdmobRewardDefault = 50,
    AdZativeAppOpen = 110,
    AdZativeBanner = 120,
    AdZativeInterDefault = 130,
    AdZativeInterOpen = 131,
    AdZativeMrecDefault = 140,
    AdZativeMrecIAP = 141,
    AdZativeMrecOpen = 142,
    AdZativeRewardDefault = 150,
}
